In [1]:
import pandas as pd
base = pd.read_csv("/home/computervision/Música/house-prices.csv")
base.head()

/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [3]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [4]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [5]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [7]:
base = pd.read_csv('/home/computervision/Música/house-prices.csv', usecols = colunas_usadas)

In [9]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [11]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [12]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [13]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [14]:
X = base.drop('price', axis = 1)
y = base.price

In [15]:
X

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0      0.090909    0.12500     0.067170  0.003108     0.0         0.0  0.00   
1      0.090909    0.28125     0.172075  0.004072     0.4         0.0  0.00   
2      0.060606    0.12500     0.036226  0.005743     0.0         0.0  0.00   
3      0.121212    0.37500     0.126038  0.002714     0.0         0.0  0.00   
4      0.090909    0.25000     0.104906  0.004579     0.0         0.0  0.00   
5      0.121212    0.56250     0.387170  0.061429     0.0         0.0  0.00   
6      0.090909    0.28125     0.107547  0.003816     0.4         0.0  0.00   
7      0.090909    0.18750     0.058113  0.005567     0.0         0.0  0.00   
8      0.090909    0.12500     0.112453  0.004210     0.0         0.0  0.00   
9      0.090909    0.31250     0.120755  0.003659     0.4         0.0  0.00   
10     0.090909    0.31250     0.246792  0.005619     0.0         0.0  0.00   
11     0.060606    0.12500     0.065660  0.003320     0.0         0.0  0.00   
12     0.090909    0.12500     0.086038  0.011740     0.2         0.0  0.00   
13     0.090909    0.21875     0.081509  0.005549     0.0         0.0  0.00   
14     0.151515    0.25000     0.114717  0.002623     0.2         0.0  0.00   
15     0.121212    0.37500     0.200755  0.002714     0.4         0.0  0.75   
16     0.090909    0.25000     0.120755  0.008190     0.4         0.0  0.00   
17     0.121212    0.12500     0.098868  0.002290     0.2         0.0  0.00   
18     0.060606    0.12500     0.068679  0.005652     0.0         0.0  0.00   
19     0.090909    0.12500     0.072453  0.005606     0.0         0.0  0.00   
20     0.121212    0.21875     0.100377  0.002702     0.0         0.0  0.00   
21     0.090909    0.34375     0.208302  0.026863     0.0         0.0  1.00   
22     0.151515    0.31250     0.149434  0.003501     0.4         0.0  0.00   
23     0.060606    0.18750     0.058868  0.005526     0.0         0.0  0.00   
24     0.090909    0.28125     0.163019  0.003622     0.4         0.0  0.00   
25     0.090909    0.25000     0.107170  0.002530     0.2         0.0  0.00   
26     0.090909    0.21875     0.163019  0.001315     0.4         0.0  0.00   
27     0.090909    0.12500     0.083774  0.000643     0.2         0.0  0.00   
28     0.090909    0.21875     0.092830  0.003550     0.0         0.0  0.00   
29     0.121212    0.31250     0.172075  0.004030     0.4         0.0  0.00   
...         ...        ...          ...       ...     ...         ...   ...   
21583  0.060606    0.12500     0.031698  0.000386     0.4         0.0  0.00   
21584  0.090909    0.31250     0.073208  0.000230     0.4         0.0  0.00   
21585  0.090909    0.31250     0.119245  0.002714     0.4         0.0  0.00   
21586  0.060606    0.31250     0.086038  0.000413     0.8         0.0  0.00   
21587  0.090909    0.31250     0.092830  0.000586     0.8         0.0  0.00   
21588  0.060606    0.18750     0.069434  0.000459     0.4         0.0  0.00   
21589  0.090909    0.31250     0.169811  0.002568     0.4         0.0  0.00   
21590  0.121212    0.43750     0.348679  0.005406     0.2         0.0  0.00   
21591  0.121212    0.34375     0.187170  0.002018     0.4         0.0  0.00   
21592  0.090909    0.28125     0.067925  0.000412     0.8         0.0  0.00   
21593  0.151515    0.46875     0.292830  0.004617     0.4         0.0  0.50   
21594  0.121212    0.34375     0.166792  0.003316     0.4         0.0  0.00   
21595  0.060606    0.28125     0.093585  0.000279     0.8         0.0  0.00   
21596  0.151515    0.34375     0.249811  0.005401     0.4         0.0  0.00   
21597  0.121212    0.40625     0.235472  0.005818     0.4         0.0  0.00   
21598  0.121212    0.31250     0.213434  0.004450     0.4         0.0  0.50   
21599  0.121212    0.37500     0.279245  0.004433     0.4         0.0  0.00   
21600  0.151515    0.46875     0.315472  0.004584     0.4         0.0  0.00   
21601  0.090909    0.31250     0.085660  0.000399     0.8

In [17]:
y

0        0.019266
1        0.060721
2        0.013770
3        0.069377
4        0.057049
5        0.150820
6        0.023934
7        0.028439
8        0.020262
9        0.032525
10       0.077049
11       0.051541
12       0.030820
13       0.042623
14       0.059672
15       0.075410
16       0.041967
17       0.053770
18       0.014951
19       0.020328
20       0.040656
21       0.252459
22       0.027541
23       0.023305
24       0.033311
25       0.020721
26       0.113049
27       0.077639
28       0.047607
29       0.084459
           ...   
21583    0.042616
21584    0.040000
21585    0.025574
21586    0.056393
21587    0.040656
21588    0.044525
21589    0.035738
21590    0.150492
21591    0.065180
21592    0.052459
21593    0.132852
21594    0.036066
21595    0.058361
21596    0.079338
21597    0.196721
21598    0.061220
21599    0.096393
21600    0.191738
21601    0.051410
21602    0.019541
21603    0.056689
21604    0.046426
21605    0.070254
21606    0.122295
21607    0

In [18]:
type(X)

pandas.core.frame.DataFrame

In [19]:
type(y)

pandas.core.series.Series

In [20]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [21]:
import tensorflow as tf

/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/computervision/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [22]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [24]:
print(colunas[10])

_NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [25]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [26]:
X_treinamento.shape

(15129, 16)

In [27]:
y_treinamento.shape

(15129,)

In [28]:
X_teste.shape

(6484, 16)

In [29]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento, 
                                                         batch_size=32, num_epochs = None, shuffle=True)

In [30]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = X_teste, y = y_teste, 
                                                         batch_size=32, num_epochs = 10000, shuffle=False)

In [31]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpgejr35it', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f1eda73c7b8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [32]:
regressor.train(input_fn=funcao_treinamento, steps = 10000)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpgejr35it/model.ckpt.
INFO:tensorflow:loss = 0.11510335, step = 1
INFO:tensorflow:global_step/sec: 170.698
INFO:tensorflow:loss = 0.006516561, step = 101 (0.589 sec)
INFO:tensorflow:global_step/sec: 271.35
INFO:tensorflow:loss = 0.021077506, step = 201 (0.372 sec)
INFO:tensorflow:global_step/sec: 255.757
INFO:tensorflow:loss = 0.012943393, step = 301 (0.388 sec)
INFO:tensorflow:global_step/sec: 211.154
INFO:tensorflow:loss = 0.009646989, step = 401 (0.473 s

INFO:tensorflow:loss = 0.02916075, step = 6801 (0.382 sec)
INFO:tensorflow:global_step/sec: 312.986
INFO:tensorflow:loss = 0.010034578, step = 6901 (0.319 sec)
INFO:tensorflow:global_step/sec: 310.742
INFO:tensorflow:loss = 0.01950275, step = 7001 (0.322 sec)
INFO:tensorflow:global_step/sec: 266.313
INFO:tensorflow:loss = 0.051765397, step = 7101 (0.376 sec)
INFO:tensorflow:global_step/sec: 261.2
INFO:tensorflow:loss = 0.010898402, step = 7201 (0.384 sec)
INFO:tensorflow:global_step/sec: 258.582
INFO:tensorflow:loss = 0.023593491, step = 7301 (0.390 sec)
INFO:tensorflow:global_step/sec: 254.586
INFO:tensorflow:loss = 0.007381279, step = 7401 (0.390 sec)
INFO:tensorflow:global_step/sec: 288.277
INFO:tensorflow:loss = 0.039139703, step = 7501 (0.346 sec)
INFO:tensorflow:global_step/sec: 277.601
INFO:tensorflow:loss = 0.022629056, step = 7601 (0.362 sec)
INFO:tensorflow:global_step/sec: 241.686
INFO:tensorflow:loss = 0.022698525, step = 7701 (0.412 sec)
INFO:tensorflow:global_step/sec: 31

In [37]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-29-18:10:41
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpgejr35it/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-29-18:11:09
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00088732206, global_step = 10000, label/mean = 0.060964715, loss = 0.028394306, prediction/mean = 0.07328833
INFO:tensorflow:Saving 'checkpoint_

In [38]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-29-18:12:21
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpgejr35it/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-01-29-18:12:49
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00081545237, global_step = 10000, label/mean = 0.06102536, loss = 0.026094476, prediction/mean = 0.07298064
INFO:tensorflow:Saving 'checkpoint_p

In [39]:
metricas_treinamento

{'average_loss': 0.00088732206,
 'global_step': 10000,
 'label/mean': 0.060964715,
 'loss': 0.028394306,
 'prediction/mean': 0.07328833}

In [40]:
metricas_teste

{'average_loss': 0.00081545237,
 'global_step': 10000,
 'label/mean': 0.06102536,
 'loss': 0.026094476,
 'prediction/mean': 0.07298064}

In [41]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, shuffle = False)

In [42]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [43]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpgejr35it/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.07096988], dtype=float32)},
 {'predictions': array([0.13114566], dtype=float32)},
 {'predictions': array([0.02092913], dtype=float32)},
 {'predictions': array([0.04812194], dtype=float32)},
 {'predictions': array([0.05607563], dtype=float32)},
 {'predictions': array([0.01908309], dtype=float32)},
 {'predictions': array([0.05701422], dtype=float32)},
 {'predictions': array([0.08713199], dtype=float32)},
 {'predictions': array([0.06057911], dtype=float32)},
 {'predictions': array([0.08818288], dtype=float32)},
 {'predictions': array([0.07315277], dtype=float32)},
 {'predictions': array([0.05350851], dtype=float32)},
 {'predictions': array([0.05052285], dtype=float32)},
 {'predictions': array([0.02130295], dtype=float32)},
 {'predictions': array([0.01263083], dtype=float32)},
 {'predictions': array([0.05248822], dtype=float32)},
 {'predictions': array([0.02782021], dtype=float32)},
 {'predictions': array([0.06510298], dtype=float32)},
 {'predictions': array([0.09

In [44]:
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpgejr35it/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [45]:
valores_previsoes


[array([0.07096988], dtype=float32),
 array([0.13114566], dtype=float32),
 array([0.02092913], dtype=float32),
 array([0.04812194], dtype=float32),
 array([0.05607563], dtype=float32),
 array([0.01908309], dtype=float32),
 array([0.05701422], dtype=float32),
 array([0.08713199], dtype=float32),
 array([0.06057911], dtype=float32),
 array([0.08818288], dtype=float32),
 array([0.07315277], dtype=float32),
 array([0.05350851], dtype=float32),
 array([0.05052285], dtype=float32),
 array([0.02130295], dtype=float32),
 array([0.01263083], dtype=float32),
 array([0.05248822], dtype=float32),
 array([0.02782021], dtype=float32),
 array([0.06510298], dtype=float32),
 array([0.09243676], dtype=float32),
 array([0.11178799], dtype=float32),
 array([0.08960906], dtype=float32),
 array([0.02427489], dtype=float32),
 array([0.05477309], dtype=float32),
 array([0.04844321], dtype=float32),
 array([0.08517602], dtype=float32),
 array([0.09403297], dtype=float32),
 array([0.10843256], dtype=float32),
 

In [46]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [47]:
valores_previsoes


array([[0.07096988],
       [0.13114566],
       [0.02092913],
       ...,
       [0.05110067],
       [0.02962317],
       [0.09032105]], dtype=float32)

In [48]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[ 616145.3 ],
       [1074985.6 ],
       [ 234584.6 ],
       ...,
       [ 464642.62],
       [ 300876.66],
       [ 763698.  ]], dtype=float32)

In [49]:
y_teste

16803    0.029508
16956    0.078689
4217     0.027541
18959    0.031475
9021     0.047869
12546    0.005115
1605     0.057311
5553     0.064787
21089    0.037370
9934     0.052459
3468     0.060328
7948     0.016393
4143     0.059148
10898    0.021770
6746     0.016991
20162    0.038718
7094     0.019148
8876     0.032590
9622     0.057180
10001    0.071475
7564     0.085246
16232    0.023475
2849     0.034885
19182    0.026754
5213     0.038426
14740    0.083541
20178    0.062426
14935    0.041967
5774     0.030820
2459     0.078590
           ...   
12229    0.059016
17940    0.070164
1100     0.196066
1633     0.013443
2717     0.121410
3121     0.163279
6046     0.022295
10000    0.050282
1089     0.040656
5897     0.037377
19031    0.091148
16283    0.028190
13930    0.022426
5697     0.063475
20460    0.428852
1229     0.050098
16489    0.031410
6000     0.050623
17886    0.018623
14312    0.074754
11287    0.031082
7895     0.019279
10247    0.032703
6601     0.028197
2857     0

In [50]:
y_teste.shape

(6484,)

In [51]:
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(6484, 1)

In [52]:
y_teste2 = scaler_y.inverse_transform(y_teste2)

In [53]:
y_teste2

array([[300000.],
       [675000.],
       [285000.],
       ...,
       [350000.],
       [219950.],
       [660000.]])

In [54]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [55]:
mae

157196.64556210782