In [1]:
import tensorflow as tf

/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/computervision/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[-1,3], [4,2]])

In [3]:
multip = tf.matmul(a, b)

In [4]:
with tf.Session() as sess:
    print(sess.run(a))
    print('\n')
    print(sess.run(b))
    print('\n')
    print(sess.run(multip))

[[1 2]
 [3 4]]


[[-1  3]
 [ 4  2]]


[[ 7  7]
 [13 17]]


In [5]:
multip2 = tf.matmul(b, a)

In [6]:
with tf.Session() as sess:
    print(sess.run(b))
    print('\n')
    print(sess.run(a))
    print('\n')
    print(sess.run(multip2))

[[-1  3]
 [ 4  2]]


[[1 2]
 [3 4]]


[[ 8 10]
 [10 16]]


In [7]:
a1 = tf.constant([[2,3],[0,1],[-1,4]])
b1 = tf.constant([[1, 2, 3], [-2, 0, 4]])

In [ ]:
multip3 = tf.matmul