In [1]:
import tensorflow as tf
import numpy as np

/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/computervision/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
X = np.array([[0.0, 0.0],
             [0.0, 1.0],
             [1.0, 0.0],
             [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [3]:
y = np.array([[0.0], [0.0], [0.0], [1.0]])
y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [4]:
W = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))
type(W)

tensorflow.python.ops.variables.RefVariable

In [5]:
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64_ref>


In [12]:
def step(x):
    return tf.cast(tf.to_float(tf.math.greater_equal(x, 1)), tf.float64)

In [6]:
init = tf.global_variables_initializer()


In [7]:
camada_saida = tf.matmul(X, W)

In [15]:
camada_saida_ativacao = step(camada_saida)

In [19]:
erro = tf.subtract(y, camada_saida_ativacao)

In [26]:
delta = tf.matmul(X, erro, transpose_a = True)
treinamento = tf.assign(W, tf.add(W, tf.multiply(delta, 0.1)))

In [31]:
with tf.Session() as sess:
    sess.run(init)
    epoca = 0
    for i in range(15):
        epoca += 1
        erro_total, _ = sess.run([erro, treinamento])
        erro_soma = tf.reduce_sum(erro_total)
        print(erro_total)
        print('Época:', epoca, 'Erro:', sess.run(erro_soma))
        W_final = sess.run(W)

[[0.]
 [0.]
 [0.]
 [1.]]
Época: 1 Erro: 1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Época: 2 Erro: 1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Época: 3 Erro: 1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Época: 4 Erro: 1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Época: 5 Erro: 1.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época: 6 Erro: 0.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época: 7 Erro: 0.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época: 8 Erro: 0.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época: 9 Erro: 0.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época: 10 Erro: 0.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época: 11 Erro: 0.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época: 12 Erro: 0.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época: 13 Erro: 0.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época: 14 Erro: 0.0
[[0.]
 [0.]
 [0.]
 [0.]]
Época: 15 Erro: 0.0


In [32]:
W_final

array([[0.5],
       [0.5]])

In [34]:
camada_saida_teste = tf.matmul(X, W_final)
camada_saida_ativacao_teste = step(camada_saida_teste)
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida_ativacao_teste))

[[0.]
 [0.]
 [0.]
 [1.]]
