In [1]:
import tensorflow as tf

/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/computervision/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
p = tf.placeholder('float', None)

In [3]:
op = p + 2

In [5]:
with tf.Session() as sess:
    #sess.run(op)
    resultado = sess.run(op, feed_dict = {p: [1, 2, 3]})
    print(resultado)

[3. 4. 5.]


In [10]:
p2 = tf.placeholder('float', [None, 5])
op2 = p2 * 5

In [12]:
with tf.Session() as sess:
    dados = [[1,2,3,4,5], [6,7,8,9,10]]
    resultado = sess.run(op2, feed_dict = {p2: dados})
    print(resultado)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
