In [1]:
import tensorflow as tf

/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/computervision/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/computervision/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [9]:
a = tf.constant([9, 8, 7], name = 'a')
b = tf.constant([1, 2, 3], name = 'b')

In [10]:
soma = a + b

In [4]:
type(a)

tensorflow.python.framework.ops.Tensor

In [5]:
print(a)

Tensor("a:0", shape=(3,), dtype=int32)


In [6]:
with tf.Session() as sess:
    print(sess.run(soma))

[10 10 10]


In [11]:
a1 = tf.constant([[1, 2, 3],[4, 5, 6]], name = 'a1')

In [12]:
type(a1)

tensorflow.python.framework.ops.Tensor

In [13]:
print(a1)

Tensor("a1:0", shape=(2, 3), dtype=int32)


In [14]:
a1.shape

TensorShape([Dimension(2), Dimension(3)])

In [15]:
b1 = tf.constant([[1, 2, 3],[4, 5, 6]], name = 'b1')

In [16]:
soma1 = tf.add(a1, b1)

In [19]:
with tf.Session() as sess:
    print(sess.run(a1))
    print('\n')
    print(sess.run(b1))
    print('\n')
    print(sess.run(soma1))

[[1 2 3]
 [4 5 6]]


[[1 2 3]
 [4 5 6]]


[[ 2  4  6]
 [ 8 10 12]]


In [22]:
a2 = tf.constant([[1, 2, 3],[4, 5, 6]], name = 'a2')
b2 = tf.constant([[1],[2]])
soma2 = tf.add(a2, b2)

In [23]:
with tf.Session() as sess:
    print(sess.run(a2))
    print('\n')
    print(sess.run(b2))
    print('\n')
    print(sess.run(soma2))

[[1 2 3]
 [4 5 6]]


[[1]
 [2]]


[[2 3 4]
 [6 7 8]]
